package com.example.Insurance.utils.types;

public enum ClaimStatus {
    REPORTED,
    DOCUMENT_COLLECTION,
    PENDING_G_REPORT,
    UNDER_TECHNICAL_REVIEW,
    QUOTATION_REQUIRED,
    PENDING_S_REPORT,
    SETTLEMENT_REVIEW,
    APPROVED,
    REJECTED,
    PAYMENT_PROCESSING,
    PAID,
    CLOSED
}