INSERT INTO users (
    etf_no,
    first_name,
    last_name,
    email,
    password,
    phone_number,
    nic,
    gender,
    date_of_birth,
    address,
    designation,
    employee_type,
    specialization,
    underwriting_limit,
    approval_level,
    branch_code,
    department,
    status,
    joined_date
) VALUES (
    'ETF1001',
    'Nimal',
    'Perera',
    'nimal.perera@company.com',
    'password123',
    '0771234567',
    '901234567V',
    'MALE',
    '1990-05-12',
    'Colombo',
    'Senior Underwriter',
    'PERMANENT',
    'Fire Insurance',
    5000000.00,
    3,
    '428',
    'General Insurance',
    'ACTIVE',
    '2018-06-15'
);

INSERT INTO users (
    etf_no,
    first_name,
    last_name,
    email,
    password,
    phone_number,
    nic,
    gender,
    date_of_birth,
    address,
    designation,
    employee_type,
    specialization,
    underwriting_limit,
    approval_level,
    branch_code,
    department,
    status,
    joined_date
) VALUES (
    'ETF1002',
    'Kasun',
    'Silva',
    'kasun.silva@company.com',
    'password123',
    '0719876543',
    '921234567V',
    'MALE',
    '1992-09-20',
    'Negombo',
    'Chief Underwriter',
    'PERMANENT',
    'Marine Insurance',
    10000000.00,
    5,
    '010',
    'Corporate Underwriting',
    'ACTIVE',
    '2016-01-10'
);