package com.example.Insurance.services.impl;

import com.example.Insurance.entities.qty.AbstractRisk;
import com.example.Insurance.entities.qty.Quotation;
import com.example.Insurance.repository.qty.QuotationRepository;
import com.example.Insurance.services.QuotationPdfService;
import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;

import java.time.LocalDateTime;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;

@Service
@RequiredArgsConstructor
public class QuotationPdfServiceImpl
        implements QuotationPdfService {

    private final QuotationRepository quotationRepository;

    @Override
    public byte[] generateQuotationPdf(Long quotationId) {

        Quotation quotation = quotationRepository.findById(quotationId)
                .orElseThrow(() ->
                        new RuntimeException("Quotation not found"));

        try {

            ByteArrayOutputStream out =
                    new ByteArrayOutputStream();

            Document document =
                    new Document(PageSize.A4);

            PdfWriter.getInstance(document, out);

            document.open();

            Font title =
                    new Font(Font.HELVETICA, 20, Font.BOLD);

            Paragraph company =
                    new Paragraph(
                            "ABC Insurance PLC",
                            title);

            company.setAlignment(Element.ALIGN_CENTER);

            document.add(company);

            document.add(new Paragraph(" "));
            PdfPTable table = new PdfPTable(2);

            table.setWidthPercentage(100);

            table.addCell("Quotation Reference");
            table.addCell(quotation.getQuotationReference());

            table.addCell("Customer");
            table.addCell(quotation.getCustomerName());

            table.addCell("Currency");
            table.addCell(quotation.getCurrency().name());

            table.addCell("Quotation Type");
            table.addCell(quotation.getQuotationType().name());

            table.addCell("Status");
            table.addCell(quotation.getStatus().name());

            document.add(table);
            AbstractRisk risk =
                    quotation.getRisks().get(0);

            document.add(new Paragraph(" "));

            document.add(new Paragraph(
                    "Risk Information"));

            PdfPTable riskTable =
                    new PdfPTable(2);

            riskTable.setWidthPercentage(100);

            riskTable.addCell("Property");

            riskTable.addCell(
                    risk.getPropertyName());

            riskTable.addCell("Location");

            riskTable.addCell(
                    risk.getLocationAddress());

            riskTable.addCell("Building SI");

            riskTable.addCell(
                    risk.getBuildingSumInsured().toString());

            riskTable.addCell("Contents SI");

            riskTable.addCell(
                    risk.getContentsSumInsured().toString());

            riskTable.addCell("Total SI");

            riskTable.addCell(
                    risk.getTotalSumInsured().toString());

            document.add(riskTable);

            document.add(new Paragraph(" "));

            document.add(new Paragraph(
                    "Premium Summary"));

            PdfPTable premium =
                    new PdfPTable(2);

            premium.setWidthPercentage(100);

            premium.addCell("Net Premium");

            premium.addCell(
                    quotation.getNetPremium().toString());

            premium.addCell("Tax");

            premium.addCell(
                    quotation.getTaxAndLeviesAmount().toString());

            premium.addCell("Grand Total");

            premium.addCell(
                    quotation.getGrandTotalPremium().toString());

            document.add(premium);

            document.add(new Paragraph(" "));

            document.add(new Paragraph(
                    "Generated By Insurance System"));

            document.add(new Paragraph(
                    LocalDateTime.now().toString()));

            document.close();

            return out.toByteArray();

        } catch (DocumentException e) {
            throw new RuntimeException(e);
        }


    }
}